go.mod
go.sum
rosetta-cli-conf/testnet/config.json
service/service_network.go

This should address the rosetta-cli `check:data` issue where the check gets stuck while expecting new blocks being produced.

Update rosetta sdk to 0.6.5 to support latest 'Synced' status

---

.gitignore
Makefile
docker/entrypoint.sh

The Rosetta API spec states persistent data must be stored at `/data` (we were storing at `/root/.avalanchego`): https://www.rosetta-api.org/docs/standard_storage_location.html

Fix default storage location

---

Makefile
go.mod
go.sum
service/rosetta.go

This PR updates `avalanchego` to [`v1.4.11`](https://github.com/ava-labs/avalanchego/releases/tag/v1.4.11).
Tested on Fuji:

V1.4.11 release

---

.dockerignore
Makefile
go.mod
go.sum
service/rosetta.go

This PR updates `avalanchego` to [`v1.4.12`](https://github.com/ava-labs/avalanchego/releases/tag/v1.4.12).

AvalancheGo@v1.4.12

---

service/service_account.go
service/types.go

```
{
"block_identifier": {
"index": 1312343,
"hash": "0x9774b69e80c152fefd18cd6afa0de9f3edffbc4cfcff01ea8639fc3eb4b7db9e"
},
"balances": [
{
"value": "156196229339915356",
"currency": {
"symbol": "AVAX",
"decimals": 18
}
}
],
"metadata": {
"nonce": "0x7"
}
}
```

Return nonce as hex

---

client/client.go
client/contract.go
client/types.go
cmd/server/config.go
mapper/amount.go
mapper/transaction.go
mapper/transaction_test.go
mapper/types.go
mocks/client/client.go
service/service_account.go
service/service_construction.go
service/service_construction_test.go

We maintain an invariant that `contractAddress` is always populated in ERC-20 metadata making this type unnecessary.
ERC-721s don't use currencies since they are transferred by index.

remove `ContractCurrency` type

---

mapper/helper.go
mapper/types.go
service/backend/cchainatomictx/backend.go
service/backend/cchainatomictx/backend_test.go
service/backend/cchainatomictx/construction.go
service/backend/cchainatomictx/construction_test.go
service/backend/common/construction.go
service/backend/pchain/backend.go
service/backend/pchain/backend_test.go
service/backend/pchain/construction.go
service/backend/pchain/construction_test.go

`/construction/derive` endpoint implementation for Bech32 addresses used for P-chain transactions (both P-chain and C-chain addresses).

/construction/derive support for p-chain and c-chain bech32 addresses

---

postman/Avalanche Rosetta.postman_collection.json
postman/README.md

Moved construction operation and metadata from pre-request scripts to `/construction/preprocess` body so that it is more obvious to use. The values from there are automagically copied to `/construction/payloads` request so that the chaining continues to work.

Simplify postman collection usage for construction requests

---

service/backend/common/construction.go
service/backend/pchain/construction.go
service/backend/pchain/construction_test.go
service/backend/pchain/types.go

Parse, combine, hash and submit implementations for P-chain. Most of the logic is written to support c-chain atomic tx support with minimal effort afterwards.

P-chain parse combine hash submit

---

mapper/transaction.go
service/backend/cchainatomictx/account.go
service/backend/cchainatomictx/account_test.go
service/backend/pchain/account.go
service/backend/pchain/account_test.go

- Adding block identifier to C-chain atomic balance requests
- Switching to use C-chain atomic tx id instead of block id for the C-chain atomic transactions in block parsing
- Adding shared memory balance support for P-chain

Account and block endpoint fixes

---

.golangci.yml
mapper/cchainatomictx/tx_parser.go
service/backend/cchainatomictx/backend.go
service/backend/cchainatomictx/backend_test.go
service/backend/cchainatomictx/construction.go
service/backend/cchainatomictx/construction_test.go
service/backend/cchainatomictx/types.go
service/backend/common/construction.go

Implementations for :
/construction/payloads
/construction/parse
/construction/combine
/construction/hash
/construction/submit
Using a single PR due to small amount of changes and their interdependencies to save back and forth time.

C chain construction rest

---

go.mod
go.sum

Upgrading Avalanchego to v1.8.5 and minimum go version to 1.18.

Version upgrades

---

mapper/pchain/tx_parser.go
mapper/pchain/tx_parser_test.go
mapper/pchain/types.go
mapper/transaction.go
mapper/transaction_test.go
mapper/types.go
service/backend/cchainatomictx/backend.go
service/backend/cchainatomictx/backend_test.go
service/service_block.go

Adding cross chain operation details to transaction metadata instead of silently excluding them from the operations. This is useful when identifying the importable UTXOs.

Add cross chain operations to transaction metadata

---

mapper/pchain/tx_parser.go
mapper/pchain/tx_parser_test.go

Fixes 2 bugs:
- AdvanceTimeTx dependency lookup error
- Block lookup regression related to multisig checks for the imported_inputs/exported_outputs

Fixing AdvanceTimeTx lookup and multisig check regression 

---

client/pchainclient.go
mapper/amount.go
mapper/cchainatomictx/helper.go
mapper/cchainatomictx/tx_builder.go
mapper/cchainatomictx/tx_parser.go
mapper/cchainatomictx/types.go
mapper/helper.go
mapper/pchain/tx_builder.go
mapper/pchain/tx_parser.go
mapper/pchain/tx_parser_test.go
mapper/pchain/types.go
service/backend/cchainatomictx/account.go
service/backend/cchainatomictx/backend.go
service/backend/cchainatomictx/construction.go
service/backend/cchainatomictx/types.go
service/backend/common/construction.go
service/backend/common/types.go
service/backend/pchain/account.go
service/backend/pchain/account_test.go
service/backend/pchain/backend.go
service/backend/pchain/block.go
service/backend/pchain/construction.go
service/backend/pchain/indexer/parser.go
service/backend/pchain/indexer/types.go
service/backend/pchain/network.go
service/backend/pchain/types.go
service/service_account.go
service/service_block.go
service/service_construction.go
service/service_network.go

- Added comments to exported types
- Made genesis timestamp definition in P-chain indexer parser more verbose
- Migrate Hash endpoint implementation to use avalanchego's id generation instead of copying it
- Added operation identifier to p-chain imported inputs/exported outputs metadata
- Fixed account balance and coins lookup to filter requested currencies and ensure currencies are properly extracted in block parsing

Multiple updates

---

service/backend/cchainatomictx/account.go
service/backend/cchainatomictx/account_test.go

Amounts are represented in nAVAX using 9 decimals when constructing and parsing C-chain atomic transactions. `/account/balance` and `/account/coins` endpoints are returning amounts in nAVAX with 18 decimals instead of 9. This PR fixes that.

Fix c-chain atomic transaction balance currencies

---

client/pchainclient.go
mocks/client/p_chain_client.go
service/backend/pchain/indexer/parser.go

Rosetta wants to use PChain block IDs as blocks identifiers and not proposerVM block IDs. Hence we want to forbid getting blocks by ID from indexer, which would assume the input hash is a proposerVM blockID and we use platformvm.GetBlock in such case

Fix Pchain Block ID usage

---

cmd/server/main.go
service/backend/pchain/backend.go
service/backend/pchain/genesis_handler.go

During startup, indexer parser calls info and indexer endpoints to figure out network id and genesis block. Adding online mode checks to prevent these calls in the offline mode.

Disable p-chain indexer related calls in offline mode

---

client/client.go
client/info_client.go
client/pchainclient.go
cmd/server/config.go
cmd/server/main.go
mocks/client/p_chain_client.go
service/backend/pchain/backend.go

When running Rosetta we cannot take for granted that avalanchego node backing Rosetta server is ready when server is started.
I did not take this into account and mistakenly try and call GetNetworkName immediately upon startup.
This PR fixes the issue

Get network name fix

---

mapper/pchain/tx_parser.go
service/backend/pchain/account_test.go
service/backend/pchain/backend.go
service/backend/pchain/block.go
service/backend/pchain/construction_test.go
service/backend/pchain/genesis_handler.go
service/backend/pchain/indexer/parser.go

Turns out it wasn't only GetNetworkName being called too early in some situations. Other avalanchego calls are issued upon server construction which causes the whole node to fail if avalanche node is not ready to serve requests immediately.
This PR addresses the issue

Lazy inits

---

client/info_client.go
cmd/server/config.go
cmd/server/main.go
mocks/client/client.go
mocks/client/p_chain_client.go
service/backend/cchainatomictx/account_test.go
service/backend/cchainatomictx/backend.go
service/backend/cchainatomictx/construction.go
service/backend/cchainatomictx/construction_test.go
service/backend/pchain/account_test.go
service/backend/pchain/backend.go
service/backend/pchain/backend_test.go
service/backend/pchain/construction.go
service/backend/pchain/construction_test.go
service/backend/pchain/genesis_handler.go
service/backend/pchain/indexer/parser.go
service/backend/pchain/indexer/parser_test.go

Calling GetNetworkID is not really necessary. All networks known to avalanchego are in its constants package.
So by using that constant package we can simplfy avalanche rosetta logic and we don't need to lazily initialize genesis.

Dropped most lazy inits in favour of Avalanchego codebase methods

---

docker/entrypoint.sh

Disable state sync by default on rosetta.

disable state-sync by default

---

mapper/pchain/tx_dependency.go
service/backend/pchain/block_test.go
service/backend/pchain/genesis_handler.go

This PR fixes a regression introduced during recent refactors to P-chain logic related to dependency transaction lookup on block parsing where the genesis allocation utxos were indexed using an incorrect transaction id. 
- Ran Fuji data validation
- Queried /block endpoint with height 4771889 which consumes UTXOs from genesis allocation
```json
{
"block": {
"block_identifier": {
"index": 4771889,
"hash": "2oD1vjLUuH1TMi8MgAe9PmFE8bbybh6YthDjKKkbTSnyLsnzZV"
},
"parent_block_identifier": {
"index": 4771888,
"hash": "M8y1ZFeVXeLc9DkpyxF8m3E3KLdsW9qc5RHQeELgAWaSco11b"
},
"timestamp": 1679169579000,
"transactions": [
{
"transaction_identifier": {
"hash": "24w1sg4fjTv1sDhjf1rDUQG7HcpFKEPyKhawJRDhzYraQFhpoP"
},
"operations": [
{
"operation_identifier": {
"index": 0
},
"type": "EXPORT_AVAX", …
```

fix genesis allocation UTXO lookup logic during block parsing

---

mapper/transaction_test.go
service/backend/cchainatomictx/construction_test.go
service/backend/pchain/construction_test.go

https://github.com/ava-labs/avalanche-rosetta/blob/master/mapper/helper.go#L99-L102

Use `mapper.DecodeToBytes` everywhere
