ava-labs/avalanche-rosetta

- Dockerfile
- Makefile
- cmd/runner/main.go
- docker/entrypoint.sh
- Use entrypoint instead of cmd
- Do not remove docker containers after execution
- Fix signal propagation
- Misc runner tweaks
> Dockerfile mods

- cmd/runner/main.go
> Process signals

- client/avm.go
- client/client.go
- client/types.go
- mapper/block.go
- mapper/transaction.go
- rosetta-cli-conf/mainnet/config.json
- service/service_block.go
- Include import/export transactions with AVAX-based assets 
- Maintain internal symbol registry
- Fix data checks
> Handle assets

- .gitignore
- client/client.go
- client/eth.go
- client/types.go
- mapper/transaction.go
- rosetta-cli-conf/mainnet/config.json
- rosetta-cli-conf/testnet/config.json
- service/service_block.go
* Return correct `gasUsed` in `trace`
* Return hex values in metadata to support large numbers
> [BUG] Use correct value for trace gas

- Makefile
- go.mod
- go.sum
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.5.2
> AvalancheGo@v1.5.2

- Makefile
- go.mod
- go.sum
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.7.2
> AvalancheGo@v1.7.2

- mapper/transaction.go
Useful for EIP-1559 transaction adoption metrics
> surface tx type in metadata

- Makefile
- docker/entrypoint.sh
- go.mod
- go.sum
- mapper/transaction.go
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.7.3
> AvalancheGo@v1.7.3

- Makefile
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.7.4
> AvalancheGo@v1.7.4

- mapper/amount.go
- mapper/helper.go
- mapper/pchain/tx_builder.go
- mapper/pchain/types.go
- mapper/types.go
- service/backend/common/construction.go
- service/backend/pchain/construction.go
- service/backend/pchain/construction_test.go
- service/helper.go
- service/service_account.go
- service/service_construction.go
- service/service_construction_test.go
/construction/preprocess and /construction/metadata endpoints for p-chain.
> /construction/preprocess and /construction/metadata endpoints for p-chain

- .gitignore
- postman/Avalanche Rosetta.postman_collection.json
- postman/README.md
- postman/test_signing_server.go
Added a postman collection to help test endpoints against testnet during development.
> Added Postman collection for all endpoints

- cmd/server/main.go
- mapper/helper.go
- mapper/pchain/tx_builder.go
- mapper/pchain/types.go
- service/backend/common/construction.go
- service/backend/common/types.go
- service/backend/pchain/account_test.go
- service/backend/pchain/backend.go
- service/backend/pchain/backend_test.go
- service/backend/pchain/construction.go
- service/backend/pchain/construction_test.go
- service/backend/pchain/types.go
Payloads endpoint implementation for P-chain importAvax, exportAvax, addValidator, addDelegator tx types.
> /construction/payloads for p-chain

- mapper/pchain/test_data.go
- mapper/pchain/tx_parser.go
- mapper/pchain/tx_parser_test.go
- mapper/pchain/types.go
- service/backend/pchain/backend.go
- service/backend/pchain/block.go
- service/errors.go
/block and /block/transaction endpoint implementations for p-chain
> /block and /block/transaction endpoints for p-chain

- client/client.go
- cmd/server/main.go
- mapper/cchainatomictx/helper.go
- mapper/cchainatomictx/tx_builder.go
- mapper/cchainatomictx/types.go
- mapper/transaction.go
- mocks/client/client.go
- service/backend/cchainatomictx/account_test.go
- service/backend/cchainatomictx/backend.go
- service/backend/cchainatomictx/backend_test.go
- service/backend/cchainatomictx/construction.go
- service/backend/cchainatomictx/construction_test.go
C chain atomic tx preprocess and metadata. This PR also contains transaction building logic as it is used to partially construct the transaction in order to estimate gas amount.
> /construction/preprocess and /construction/metadata endpoints for c-chain atomic transactions

- Makefile
- go.mod
- go.sum
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.8.5
> AvalancheGo@v1.8.5

- mapper/pchain/tx_parser.go
- mapper/pchain/types.go
Add signer metadata to add permissionless validator tx stake output operatinos
> add signer to permissionless validator tx output metadata

- go.mod
- go.sum
- mapper/pchain/types.go
- service/backend/pchain/account.go
- service/backend/pchain/block.go
- service/backend/pchain/indexer/parser.go
- 1.9.0 compatibility
- added comments in indexer parser
- added import aliases in indexer parser
> v1.9.0 support and other fixes requested in #123

- mapper/cchainatomictx/tx_builder.go
- mapper/pchain/helper.go
- mapper/pchain/tx_builder.go
- service/backend/cchainatomictx/construction.go
- service/backend/cchainatomictx/types.go
- service/backend/common/construction.go
- service/backend/common/types.go
- service/backend/pchain/construction.go
- service/backend/pchain/types.go
Uninitialized means they will report empty ID for instance. I really think we don't want that
> Fixing some uninitialized Txs

- .gitignore
- Makefile
- README.md
- cmd/server/config.go
- cmd/server/main.go
- rosetta-cli-conf/testnet/avalanche_unwrap.ros
- rosetta-cli-conf/testnet/config_unwrap.json
- service/config.go
- service/helper.go
- service/service_construction.go
- service/service_construction_test.go
- service/types.go
Adding support for Rosetta to call unwrap on a configured list of contracts
https://github.com/ava-labs/avalanche-rosetta/pull/101 has been rebased on top of this branch
> Avalanche Bridge Support

- Makefile
- go.mod
- go.sum
- service/rosetta.go
https://medium.com/avalancheavax/cortina-x-chain-linearization-a1d9305553f6
> AvalancheGo@v1.10.0

- Makefile
- go.mod
- go.sum
- postman/test_signing_server.go
- service/backend/cchainatomictx/backend.go
- service/backend/cchainatomictx/construction.go
- service/backend/common/construction.go
- service/backend/pchain/backend.go
- service/backend/pchain/construction.go
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.15
> AvalancheGo@v1.10.15

- Makefile
- go.mod
- go.sum
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.19
> AvalancheGo@v1.10.19

- Dockerfile
- Makefile
- go.mod
- go.sum
- service/rosetta.go
https://github.com/ava-labs/avalanchego/releases/tag/v1.11.9
> Update avalanchego version to v1.11.9
